### ISSUE TITLE
Autosuggest payee based on location

### ISSUE THREAD

**Issue by witriew** [jasonpetsod/loony#3]
Copied from review:

> > I half enjoyed the auto-filled payee based on location (when it worked). Should that be stored here? Or maybe do this like the new Swarm UI (find places near me) in the UX?
> Yup, agree. We probably want to use a combination of this: the app could use both the Foursquare API and historical locations stored here to suggest to the user which places are nearby. If the user chooses a place, we store its latitude and longitude here for future use. If the user doesn't choose a place listed in Foursquare, we store the current location attributed to the payee.
> 
> We'd need some sort of reverse geo-search though. Firebase doesn't give one to us for free so we'd need to come up with a new schema that can be searched efficiently for this.

**Comment by jasonpetsod** [comment]
Moved to https://loony.phacility.com/T21.
